# Generated by Django 4.1.2 on 2023-02-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to=materials.models.get_upload_path),
        ),
        # migrations.CreateModel(
        #     name='UserProfile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_approved', models.BooleanField(default=False)),
        #         ('courses', models.ManyToManyField(to='materials.course')),
        #         ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
