# Generated by Django 4.1.2 on 2023-02-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_userprofile_courses_userprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('materials', models.ManyToManyField(to='materials.material')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.topic')),
            ],
        ),
    ]
