# Generated by Django 4.1.2 on 2023-02-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_remove_course_student_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        # migrations.AddField(
        #     model_name='course',
        #     name='lesson1',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AddField(
        #     model_name='material',
        #     name='title',
        #     field=models.CharField(max_length=80, null=True),
        # ),
        # migrations.AddField(
        #     model_name='topic',
        #     name='lesson',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        migrations.AlterField(
            model_name='languagelevel',
            name='level',
            field=models.CharField(choices=[('ALL', 'ALL'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, to='materials.material'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.languagelevel'),
        ),
    ]
