# Generated by Django 4.1.2 on 2023-03-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0006_remove_lesson_topic_course_lesson1_lesson_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
         migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
