# Generated by Django 4.1.2 on 2023-03-02 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0007_course_student'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='course',
        #     name='lesson1',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        # migrations.AddField(
        #     model_name='material',
        #     name='title',
        #     field=models.CharField(max_length=80, null=True),
        # ),
        # migrations.AddField(
        #     model_name='topic',
        #     name='lesson',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
