# Generated by Django 4.1.2 on 2023-03-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0009_delete_userprofile_course_lesson1_lesson_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
                migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='materials.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField(null=True))
            ],
        ),
        # migrations.AddField(
        #     model_name='course',
        #     name='lesson1',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        # migrations.AddField(
        #     model_name='material',
        #     name='title',
        #     field=models.CharField(max_length=80, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='courses',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course'),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='is_approved',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='phone',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='user',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='materials',
        #     field=models.ManyToManyField(blank=True, to='materials.material'),
        # ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='topic',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.topic'),
        # ),
    ]
