# Generated by Django 4.1.2 on 2023-03-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0010_remove_course_student_course_lesson1_material_title_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='course',
        #     name='lesson1',
        #     field=models.ManyToManyField(blank=True, to='materials.lesson'),
        # ),
        # migrations.AddField(
        #     model_name='material',
        #     name='title',
        #     field=models.CharField(max_length=80, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='materials',
        #     field=models.ManyToManyField(blank=True, to='materials.material'),
        # ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='topic',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.topic'),
        # ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course'),
        ),
    ]
