# Generated by Django 4.1.2 on 2023-03-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_course_lesson1_material_title_alter_course_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ManyToManyField(blank=True, to='materials.material'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.topic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
