# Generated by Django 4.1.2 on 2023-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_course_lesson1_material_title_alter_course_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson1',
            field=models.ManyToManyField(blank=True, related_name='coursesl', to='materials.lesson'),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),        
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='coursesm', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='lessonsm', to='materials.material'),
        ),
    ]
