# Generated by Django 4.1.2 on 2023-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_course_lesson1_material_title_alter_course_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
