# Generated by Django 4.1.2 on 2023-03-14 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0015_commens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commens',
            options={'ordering': ['-time_created'], 'verbose_name': 'Comment'},
        ),
        migrations.AlterField(
            model_name='commens',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
