version: "3.9"
services:
  english_learning:
    container_name: my_web
    build: ./english_learning
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    volumes:
      - ./english_learning:/app
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    container_name: mysql-1
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  bot:
    container_name: my_bot
    build: ./bot
    command: python lang_bot.py
    ports:
      - "5000:5000"
    volumes:
      - ./bot:/app
      # - ./bot/handlers:/app/handlers
    depends_on:
      - mysql
    links:
      - mysql:mysql

volumes:
  mysql_data:
    driver: local